theme = "dracula"

[editor]
cursorline = true
line-number = "relative"
color-modes = true

[editor.statusline]
right =  ["diagnostics", "selections", "register", "file-encoding", "position-percentage", "position"] 

[editor.soft-wrap]
enable = true

[editor.whitespace]
render = "all"

[editor.cursor-shape]
normal = "block"
insert = "bar"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal."+"]
f = ":pipe jq"
l = ":pipe jq '.[] | length'"
j = ":pipe jq 'fromjson'"
