[language-server.pyright]
command = "pyright-langserver"

[language-server.ruff]
command = "ruff-lsp"
config = { settings = { run = "onSave" } }

[language-server.lua]
command = "lua-language-server"

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
language-servers = ["lua"]
